SELECT STUDENTSEQ.currval FROM DUAL;
INSERT INTO STUDENT VALUES (STUDENTSEQ.nextval, ‘BISHAL’, ‘JAVA’, 7902);

SELECT * FROM EMP WHERE ROWNUM <= 3; 

SELECT ROWID, ename FROM emp WHERE deptno = 20;